### ISSUE TITLE
Prototype output Validity Sensors, Inc. 0x138a:0x0097

### ISSUE THREAD

**Issue by ilanco** [nmikhailov/Validity90#12]
This is the fingerprint reader on a Lenovo X270

[0x138a-0x0097.log](https://github.com/nmikhailov/Validity90/files/1328725/0x138a-0x0097.log)

![img](https://user-images.githubusercontent.com/912465/30798786-778e5c20-a1e3-11e7-83f4-73f08f7d6b5b.png)

**Comment by nmikhailov** [comment]
Thanks. Prototype was updated, it doesn't output images anymore since they are not available on 0097. Hovewer it can now check fingerprints againts internal db. Please join our [gitter](https://gitter.im/Validity90/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link) to stay in touch and receive project updates.
