### ISSUE TITLE
Prototype output for Lenovo T570

### ISSUE THREAD

**Issue by hinxx** [nmikhailov/Validity90#14]
https://gist.github.com/hinxx/b769c09094184346f5ca168d9451331c

Thanks!

**Comment by PofMagicfingers** [comment]
Another one : https://gist.github.com/PofMagicfingers/4799d8a3dc52926e68d44e8db0925539

Thanks !

**Comment by pciavald** [comment]
https://gist.github.com/pciavald/611aad3153e0d3be74a4ff12cd40ff28

![img](https://user-images.githubusercontent.com/3384097/33232990-04521c26-d210-11e7-8431-49b4f1a19a22.png)

**Comment by petrmanek** [comment]
Here's another one: https://gist.github.com/petrmanek/8d4c2d86e7c902b7d6185f922ee3e322
![img](https://user-images.githubusercontent.com/1297382/34467324-7c546076-eeee-11e7-83bd-43c92add036a.png)

**Comment by nmikhailov** [comment]
Thanks. Prototype was updated, it doesn't output images anymore since they are not available on 0097. Hovewer it can now check fingerprints againts internal db. Please join our [gitter](https://gitter.im/Validity90/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link) to stay in touch and receive project updates.
