### ISSUE TITLE
Add support for 138a:003f Validity Sensors, Inc. VFS495 Fingerprint Reader

### ISSUE THREAD

**Issue by jontis** [nmikhailov/Validity90#52]
[usb_output.txt](https://github.com/nmikhailov/Validity90/files/2546315/usb_output.txt)

**Comment by parkerlreed** [comment]
Only the proprietary blob is available. https://aur.archlinux.org/packages/vfs495-daemon/

This works with latest libfrpint from git.

**Comment by jasontibbitts** [comment]
I'm not sure how this ticket relates to this project.  The project is about a selected few validity sensors, and the 138a:003f is something quite different.

I guess this project has sort of turned into a dumping ground for anything related to validity fingerprint readers, which is unfortunate as it only serves to confuse people.

**Comment by iQ-kz** [comment]
i did it :)
it took almost a week on linux mint x64 xfce with autoupdate. 
and it works. but...
i was to use already compiled binaries from HP, there's no other way.
(hereinafter as ChatGPT says)
and there's the problem: these binaries are not the same as for windows. 
while in windows there is a routine for calibration and hard-resetting the scanner, in linux driver's core it absent.
so my scanner worked only when:
1. i cleared the scanned with spirit within a minute before usage
2. i washed my hands heavily before usage
3. i put a cooling fan near the scanner to blow on it
4. i had only a couple of seconds prior to "switching from COLD to WARM state" in debug message
5. and after this scanner doesn't work until hard reset with unplugging power
ChatGPT says that this probably is because when the scanner switches to "WARM" state, it starts seeing some "phantom fingerprint" on it, and this is because the laptop is old and scanning element degrades. in windows (it says) there is a calibrating routine, that's why even an old scanner continues working.

anyway, how did i fix it:
i downloaded HP servicepack with linux binaries, and i cloned vfs495_fprintd into a custom fprintd. then i made a couple of bugfixes (like changing "@0@".format(value) to f"@value@", and apt-installed lots of libraries (but none was deprecated!)
i disabled all other drivers except vfs495, and compiled everything by adding correct "vfs495" links to files above the same for "vfs5011" - this means i had a proper "vfs495.c" also from one of these repos.

it took about three days, and now my mint GUI "Fingerprints" app asks me to swipe my finger and twice i've been validated with "pattern 34/24: valid" in debug and it works. but this routine is a rare cornercase, in 999/1000 tryouts it says "unknown error" and either debug says "switching to "WARM state, fingerprint acquired, cannot be recognized" within a second after starting the routine and without a real finger, or tons of other errors like "port busy", "cannot handle", "device is suspended" etc.
and each time for a new try i need to restart my laptop, because this scanner doesn't reboot when i turn it off/on using linux commands to suspend/disable/poweroff it.

the best choice is to forget about this fingerprint and let it be useless.
